project:
  type: website
  output-dir: docs

website:
  title: "Faculty Enrichment Program in Applied Malaria Modeling"
  reader-mode: true
  favicon: numalaria_logo.png
  sidebar: 
    style: floating   
    title: "Faculty Enrichment Program in Applied Malaria Modeling"
    logo: numalaria_logo.png
    background: white
    foreground: dark
    collapse-level: 1
    search: true
    contents:  
      - section: "2023 Program"
        contents: 
          - index.qmd
          
      - section: "EMOD How-To Guides"
        contents: 
         
          - guides/demographics_guide.qmd
          
      
      - text: "<br><span style='color: red; font-weight:bold;'>Voir le Site en Français</span>" 
        url: https://numalariamodeling.github.io/FE-2023-site-web-francais/

    tools: 
      - icon: github
        menu: 
          - text: Website Source Code
            url: https://github.com/

  page-footer:
    center: © NU Malaria Modeling 2024
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    

editor: source
